services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: keycloak
    env_file:
      - .env
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./tls.key:/etc/cert/tls.key:ro
      - ./tls.crt:/etc/cert/tls.crt:ro
      - ./keycloak.conf:/opt/keycloak/keycloak.conf
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: --config-file=/opt/keycloak/keycloak.conf start --import-realm
    depends_on:
      - postgresql
    networks:
      keycloak-playground:


  postgresql:
    image: postgres:17
    container_name: postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      keycloak-playground:
    volumes:
      - postgresql-data:/var/lib/postgresql/data

networks:
  keycloak-playground:
    driver: bridge
  
volumes:
  postgresql-data:
